let mapleader = ","

set nocompatible
call pathogen#infect()
call pathogen#helptags()

filetype plugin indent on
runtime! config/**/*.vim

" --------------------------------------------------------------------------------
" For finding files more easily
" --------------------------------------------------------------------------------
set path+=**
set wildmenu

" --------------------------------------------------------------------------------
" configure editor with tabs and nice stuff...
" --------------------------------------------------------------------------------
syntax on               " syntax highlighting
set expandtab           " enter spaces when tab is pressed
set tabstop=4           " use 4 spaces to represent tab
set softtabstop=4
set shiftwidth=4        " number of spaces to use for auto indent
set autoindent          " copy indent from current line when starting a new line
set backspace=indent,eol,start " make backspaces more powerfull
set cursorline
"set ruler                           " show line and column number
set showcmd             " show (partial) command in status line
set number
set noshowmode
set laststatus=2
set wrap
set textwidth=0 wrapmargin=0
set display+=lastline

" --------------------------------------------------------------------------------
" Colorscheme
" --------------------------------------------------------------------------------
let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ }
colorscheme angr
"colorscheme afterglow

"highlight CursorLineNr ctermfg=LightGray

" --------------------------------------------------------------------------------
" Shortucts
" --------------------------------------------------------------------------------
map <leader>o :NERDTreeToggle<CR>
let NERDTreeQuitOnOpen = 1

inoremap <C-e> <C-o>$
inoremap <C-a> <C-o>0
map <C-b> :w! \| !compiler <c-r>%<CR>
" Open corresponding .pdf/.html or preview
map <leader>p :!opout <c-r>%<CR><CR>
command! MakeTags !ctags -R .

nnoremap k gk
nnoremap j gj
nnoremap 0 g0
nnoremap $ g$
nnoremap ^ g^

" --------------------------------------------------------------------------------
" configure expanding of tabs for various file types
" --------------------------------------------------------------------------------
au BufRead,BufNewFile *.py set expandtab
au BufRead,BufNewFile *.c set noexpandtab
au BufRead,BufNewFile *.h set noexpandtab
au BufRead,BufNewFile Makefile* set noexpandtab

" --------------------------------------------------------------------------------
"  Latex
" --------------------------------------------------------------------------------
autocmd FileType tex inoremap ,bf \textbf{}<Esc>T{i

" --------------------------------------------------------------------------------
" Search settings
" --------------------------------------------------------------------------------
set incsearch           " search as characters are entered
"set hlsearch            " highlight matches

