let mapleader = ","

set nocompatible
call pathogen#infect()
call pathogen#helptags()

filetype plugin indent on
runtime! config/**/*.vim
runtime snippets.vim

" --------------------------------------------------------------------------------
" For finding files more easily
" --------------------------------------------------------------------------------
set path+=**
set wildmenu
set wildignore+=*.o,*.aux,*.fls,*.out,*.blg,.git,*.pyc " Ignore these files when completing
" --------------------------------------------------------------------------------
" configure editor with tabs and nice stuff...
" --------------------------------------------------------------------------------
syntax on               " syntax highlighting
set expandtab           " enter spaces when tab is pressed
set tabstop=4           " use 4 spaces to represent tab
set softtabstop=4
set shiftwidth=4        " number of spaces to use for auto indent
set autoindent          " copy indent from current line when starting a new line
set backspace=indent,eol,start " make backspaces more powerful
set cursorline
"set ruler                           " show line and column number
set showcmd             " show (partial) command in status line
set number relativenumber
set numberwidth=6
set noshowmode
set laststatus=2
set wrap
set textwidth=0 wrapmargin=0
set display+=lastline

" --------------------------------------------------------------------------------
" Color scheme
" --------------------------------------------------------------------------------
"colorscheme angr
colorscheme nord
let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ }


" --------------------------------------------------------------------------------
" Shortcuts
" --------------------------------------------------------------------------------
map <leader>o :NERDTreeToggle<CR>
let NERDTreeQuitOnOpen = 1

inoremap <C-e> <C-o>$
inoremap <C-a> <C-o>0
map <C-b> :w! \| !compiler <c-r>%<CR>
" Open corresponding .pdf/.html or preview
map <leader>p :!opout <c-r>%<CR><CR>
command! MakeTags !ctags -R .

nnoremap k gk
nnoremap j gj
nnoremap 0 g0
nnoremap $ g$
nnoremap ^ g^

" --------------------------------------------------------------------------------
" configure expanding of tabs for various file types
" --------------------------------------------------------------------------------
au BufRead,BufNewFile *.py set expandtab
au BufRead,BufNewFile *.c set noexpandtab
au BufRead,BufNewFile *.h set noexpandtab
au BufRead,BufNewFile Makefile* set noexpandtab



" --------------------------------------------------------------------------------
" Search settings
" --------------------------------------------------------------------------------
set incsearch           " search as characters are entered
"set hlsearch            " highlight matches

augroup vimrcEx
  autocmd!

  " When editing a file, always jump to the last known cursor position.
  " Don't do it for commit messages, when the position is invalid, or when
  " inside an event handler (happens when dropping a file on gvim).
  autocmd BufReadPost *
    \ if &ft != 'gitcommit' && line("'\"") > 0 && line("'\"") <= line("$") |
    \   exe "normal g`\"" |
    \ endif

  " Set syntax highlighting for specific file types
  "
  "
  "
  "
  "
  "
  "
  "
  "
  "
  autocmd BufRead,BufNewFile *.md set filetype=markdown
  autocmd BufRead,BufNewFile .{jscs,jshint,eslint}rc set filetype=json
  autocmd BufRead,BufNewFile aliases.local,zshrc.local,*/zsh/configs/* set filetype=sh
  autocmd BufRead,BufNewFile gitconfig.local set filetype=gitconfig
  autocmd BufRead,BufNewFile tmux.conf.local set filetype=tmux
  autocmd BufRead,BufNewFile vimrc.local set filetype=vim
augroup END

" Tab completion
" will insert tab at beginning of line,
" will use completion if not at beginning
set wildmode=list:longest,list:full
function! InsertTabWrapper()
    let col = col('.') - 1
    if !col || getline('.')[col - 1] !~ '\k'
        return "\<Tab>"
    else
        return "\<C-p>"
    endif
endfunction
inoremap <Tab> <C-r>=InsertTabWrapper()<CR>
inoremap <S-Tab> <C-n>


" --------------------------------------------------------------------------------
"  Spell checking stuff
" --------------------------------------------------------------------------------
map <F6> :setlocal spell! spelllang=en_us<CR>
" --------------------------------------------------------------------------------
"  Autoreload stuff
" --------------------------------------------------------------------------------
map <leader>vimrc :tabe $MYVIMRC<cr>
autocmd bufwritepost .vimrc source $MYVIMRC
" --------------------------------------------------------------------------------
"  Copy and paste from clipboard
" --------------------------------------------------------------------------------
vnoremap <C-c> "*y :let @+=@*<CR>
map <C-x> "+P

