let mapleader = ","

set nocompatible
call pathogen#infect()
call pathogen#helptags()

filetype plugin indent on


set number
set noshowmode
set laststatus=2

runtime! config/**/*.vim

" Colorscheme
let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ }
colorscheme angr
"colorscheme afterglow


" Shortucts
map <leader>o :NERDTreeToggle<CR>
inoremap <C-e> <C-o>$
inoremap <C-a> <C-o>0
map <C-b> :w! \| !compiler <c-r>%<CR>
" Open corresponding .pdf/.html or preview
map <leader>p :!opout <c-r>%<CR><CR>

nnoremap k gk
nnoremap j gj
nnoremap 0 g0
nnoremap $ g$
nnoremap ^ g^

" configure expanding of tabs for various file types
au BufRead,BufNewFile *.py set expandtab
au BufRead,BufNewFile *.c set noexpandtab
au BufRead,BufNewFile *.h set noexpandtab
au BufRead,BufNewFile Makefile* set noexpandtab

" --------------------------------------------------------------------------------
" configure editor with tabs and nice stuff...
" --------------------------------------------------------------------------------
set expandtab           " enter spaces when tab is pressed
set textwidth=120       " break lines when line length increases
set tabstop=4           " use 4 spaces to represent tab
set softtabstop=4
set shiftwidth=4        " number of spaces to use for auto indent
set autoindent          " copy indent from current line when starting a new line

" make backspaces more powerfull
set backspace=indent,eol,start

set ruler                           " show line and column number
syntax on               " syntax highlighting
set showcmd             " show (partial) command in status line

" -------------------------------------------
"  Latex
"  -----------------------------------------
autocmd FileType tex inoremap ,bf \textbf{}<Esc>T{i

