let mapleader = ","
set t_Co=256 
" --------------------------------------------------------------------------------
" General settings for plugins and such
" --------------------------------------------------------------------------------
set nocompatible
call pathogen#infect()
call pathogen#helptags()
filetype plugin indent on
runtime! config/**/*.vim
" --------------------------------------------------------------------------------
" Snippets
" --------------------------------------------------------------------------------
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<s-tab>"
let g:UltiSnipsSnippetDirectories=[$HOME.'/.vim/UltiSnips']
"runtime snippets.vim
" --------------------------------------------------------------------------------
" General behavior
" --------------------------------------------------------------------------------
syntax on               " syntax highlighting
set expandtab           " enter spaces when tab is pressed
set tabstop=4           " use 4 spaces to represent tab
set softtabstop=4
set shiftwidth=4        " number of spaces to use for auto indent
set autoindent          " copy indent from current line when starting a new line
set backspace=indent,eol,start " make backspaces more powerful
set number relativenumber
set numberwidth=6
set noshowmode
set laststatus=2
set wrap
set textwidth=0 wrapmargin=0
set display+=lastline
set scrolloff=5
set autochdir
"set cursorline
"set ruler                           " show line and column number
"set showcmd             " show (partial) command in status line
set autoread
" --------------------------------------------------------------------------------
" Configure expanding of tabs for various file types
" --------------------------------------------------------------------------------
au BufRead,BufNewFile *.py set expandtab
au BufRead,BufNewFile *.c set noexpandtab
au BufRead,BufNewFile *.h set noexpandtab
au BufRead,BufNewFile Makefile* set noexpandtab
" --------------------------------------------------------------------------------
"  some NERDTRree stuff
" --------------------------------------------------------------------------------
"autocmd vimenter * NERDTree
"nnoremap <Leader>f :NERDTreeToggle<Enter>
"let NERDTreeMinimalUI = 1
"let NERDTreeDirArrows = 1
"autocmd BufEnter * if bufname('#') =~# "^NERD_tree_" | b# | endif"
" --------------------------------------------------------------------------------
"  Some buffers things and appearance
" --------------------------------------------------------------------------------
nnoremap <leader>q :bp<cr>:bd #<cr>
set fillchars+=vert:│
" --------------------------------------------------------------------------------
" Search settings
" --------------------------------------------------------------------------------
set incsearch           " search as characters are entered
set ignorecase
" --------------------------------------------------------------------------------
" For finding files more easily
" --------------------------------------------------------------------------------
set path+=**
set wildmenu
set wildignore+=*.o,*.aux,*.fls,*.out,*.blg,.git,*.pyc " Ignore these files when completing
" --------------------------------------------------------------------------------
" Color scheme
" --------------------------------------------------------------------------------
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#show_buffers = 1
let g:airline#extensions#tabline#show_splits = 0
let g:airline#extensions#tabline#show_tabs = 1
let g:airline#extensions#tabline#show_tab_nr = 0
let g:airline#extensions#tabline#show_tab_type = 0
let g:airline#extensions#tabline#close_symbol = '×'
let g:airline#extensions#tabline#show_close_button = 0
let g:airline#extensions#tabline#formatter = 'unique_tail'
"colorscheme wal
"colorscheme github
colorscheme nord
" --------------------------------------------------------------------------------
" Shortcuts
" --------------------------------------------------------------------------------
set statusline+=%{gutentags#statusline()}
let g:gutentags_cache_dir = '~/.cache/gutentags'
let g:gutentags_project_root = ['.root', '.git']
let g:gutentags_generate_on_new = 1
let g:gutentags_generate_on_missing = 1
let g:gutentags_generate_on_write = 1
let g:gutentags_generate_on_empty_buffer = 0
map <leader>p :!opout <c-r>%<CR><CR>
command! MakeTags !ctags -R .
" --------------------------------------------------------------------------------
" Navigation
" --------------------------------------------------------------------------------
nnoremap k gk
nnoremap j gj
nnoremap 0 g0
nnoremap $ g$
nnoremap ^ g^
inoremap <C-e> <C-o>$
inoremap <C-a> <C-o>0
map <C-j> :bp<CR>
map <C-k> :bn<CR>
" --------------------------------------------------------------------------------
" Jump to last known position
" --------------------------------------------------------------------------------
augroup vimrcEx
  autocmd!
  " When editing a file, always jump to the last known cursor position.
  " Don't do it for commit messages, when the position is invalid, or when
  " inside an event handler (happens when dropping a file on gvim).
  autocmd BufReadPost *
    \ if &ft != 'gitcommit' && line("'\"") > 0 && line("'\"") <= line("$") |
    \   exe "normal g`\"" |
    \ endif

  " Set syntax highlighting for specific file types
  autocmd BufRead,BufNewFile *.md set filetype=markdown
  autocmd BufRead,BufNewFile .{jscs,jshint,eslint}rc set filetype=json
  autocmd BufRead,BufNewFile aliases.local,zshrc.local,*/zsh/configs/* set filetype=sh
  autocmd BufRead,BufNewFile gitconfig.local set filetype=gitconfig
  autocmd BufRead,BufNewFile tmux.conf.local set filetype=tmux
  autocmd BufRead,BufNewFile vimrc.local set filetype=vim
augroup END

" Tab completion
" will insert tab at beginning of line,
" will use completion if not at beginning
"set wildmode=list:longest,list:full
"function! InsertTabWrapper()
    "let col = col('.') - 1
    "if !col || getline('.')[col - 1] !~ '\k'
        "return "\<Tab>"
    "else
        "return "\<C-p>"
    "endif
"endfunction
"inoremap <Tab> <C-r>=InsertTabWrapper()<CR>
"inoremap <S-Tab> <C-n>

" --------------------------------------------------------------------------------
"  Spell checking stuff
" --------------------------------------------------------------------------------
map <F6> :setlocal spell! spelllang=en_gb<CR>
" --------------------------------------------------------------------------------
"  Autoreload stuff
" --------------------------------------------------------------------------------
map <leader>vi :e $MYVIMRC<cr>
autocmd bufwritepost .vimrc source $MYVIMRC
" --------------------------------------------------------------------------------
"  Copy and paste from clipboard
" --------------------------------------------------------------------------------
vnoremap <C-c> "*y :let @+=@*<CR>
map <C-z> "+P
map <C-x> "+p
" --------------------------------------------------------------------------------
" Vim Wiki configuration 
" --------------------------------------------------------------------------------
let g:vimwiki_list = [{'path': '~/.notes/', 'syntax': 'markdown', 'ext': '.md'},
            \ {'path': '~/.notes/opc/', 'syntax': 'markdown', 'ext': '.md'}]

nnoremap <leader>l :VimwikiToggleListItem<CR>
" --------------------------------------------------------------------------------
" Vim Calendar
" --------------------------------------------------------------------------------
"let g:calendar_google_calendar = 1
"nnoremap <leader>c :Calendar -first_day=monday<CR>
"autocmd FileType calendar nmap <buffer> h <Plug>(calendar_prev)
"autocmd FileType calendar nmap <buffer> l <Plug>(calendar_next)
" --------------------------------------------------------------------------------
" Some mail stuff that are being ignored otheriwse
" --------------------------------------------------------------------------------
autocmd FileType mail set fo-=t
autocmd FileType mail set tw=0


" Quick run via <F5>
nnoremap <C-b> :call <SID>compile_and_run()<CR>

function! s:compile_and_run()
    exec 'w'
    if &filetype == 'python'
        "exec "AsyncRun! gcc % -o %<; time ./%<"
        exec "Dispatch python %"
    "elseif &filetype == 'cpp'
       "exec "AsyncRun! g++ -std=c++11 % -o %<; time ./%<"
    "elseif &filetype == 'java'
       "exec "AsyncRun! javac %; time java %<"
    "elseif &filetype == 'sh'
       "exec "AsyncRun! time bash %"
    "elseif &filetype == 'python'
       "exec "AsyncRun! time ipython %"
    elseif &filetype == 'tex'
        exec "Dispatch! latexmk -pdf %"
    endif
endfunction

" asyncrun now has an option for opening quickfix automatically
"let g:asyncrun_open = 5
nnoremap <leader>c :ccl<CR>
let g:goyo_width = 100
