#! /bin/sh

sxhkd &
xrdb /home/joo/.Xresources &
/home/joo/.config/polybar/launch.sh &
compton &
xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape' &
feh --bg-scale /home/joo/Pictures/wallpapers/curls.png &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap          24

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^9' state=floating follow=on
bspc rule -a Firefox desktop='^1'
