#! /bin/sh

sxhkd &
xrdb /home/joo/.Xresources &
xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape' &
feh --bg-scale /home/joo/Pictures/wallpapers/house_lake.jpg &

bspc monitor DP-0 -d 1 3 8 10
bspc monitor DVI-I-1 -d 2 4 5 6 7 9

bspc config top_padding         0
bspc config border_width         2
bspc config window_gap          24

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Yad state=floating
bspc rule -a Blender state=floating
bspc rule -a Casalogger state=floating
bspc rule -a "*:casa-viewer" state=floating
bspc rule -a Blueman-manager state=floating
bspc rule -a Matplotlib state=floating
bspc rule -a " " state=floating
bspc rule -a Gimp desktop=9 state=floating
bspc rule -a Firefox desktop=1
bspc rule -a mpv desktop=8
bspc rule -a spotify desktop=10

. $HOME/.config/polybar/launch.sh
kill $(pidof compton)
compton

