#! /bin/sh

sxhkd &
xrdb /home/joo/.Xresources &
/home/joo/.config/polybar/launch.sh &
compton &
nm-applet &
xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape' &
feh --bg-scale /home/joo/Pictures/wallpapers/enso_color.png &
wal -R

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config top_padding         0
bspc config border_width         6
bspc config window_gap          16

bspc config active_border_color #FFA71A

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Yad state=floating
bspc rule -a feh state=floating
bspc rule -a Ds9.tcl state=floating
bspc rule -a lutris state=floating
bspc rule -a blueman-manager state=floating
bspc rule -a Matplotlib state=floating
bspc rule -a herschel-ia-gui-apps-HipeStarter state=floating
bspc rule -a " " state=floating
bspc rule -a Firefox desktop='^1'
bspc rule -a GoPanda2 desktop='^7'
bspc rule -a Sabaki desktop='^7'
bspc rule -a mpv desktop='^8'
bspc rule -a Gimp desktop='^9' state=floating follow=on
bspc rule -a spotify desktop='^10'
